path:
  mangastate:
    currentstate: src/main/resources/mangaState.json
    lirescanstate: src/main/resources/lirescanState.json
    
thread:
  minutesbeforenewupdate:
    lirescan: 1000
  
url:
  mangawebsite:
    lirescan: https://www.lirescan.me/
    