path:
  mangaimgurl: https://notImplementedURL.com
  mangaimgs:
    ajin: Ajin15.jpg
    attackontitan: ShingekiNoKyojin26.jpg
    blackclover: BlackClover8.jpg
    boruto: Boruto5.jpg
    chainsawman: Chainsawman1.jpg
    fairtytail100yearsquest: FairyTail100YearsQuest5.jpg
    enigma: Enigma5.jpg
    jujutsukaisen: JujutsuKaisen1.jpg
    myheroacademia: MyHeroAcademia27.jpg
    onepiece: OnePiece93.jpg
    onepunchman: OnePunchManSpecial.jpg
    onepunchmanone: OnePunchManOne.jpg
    platiniumend: PlatiniumEnd5.jpg
    sololeveling: SoloLevelingSeason2.jpg
    thepromisedneverland: ThePromisedNeverLand5.jpg
    tokyorevengers: TokyoRevengers13.jpg
    worldtrigger: WorldTrigger19.jpg
  mangastate:
    currentstate: src/main/resources/mangaState.json
    lirescanstate: src/main/resources/lirescanState.json
    lelscanstate: src/main/resources/lelscanState.json
    mangareaderstate: src/main/resources/mangareaderState.json
    
thread:
  minutesbeforenewupdate:
    lirescan: 1000
  
url:
  mangawebsite:
    lirescan: https://www.lirescan.me/
    lelscan: https://www.lelscan-vf.me/
    mangareader: https://www.mangareader.net/
    